Whitespace cleanup

diff --git a/bin/convert-tsql b/bin/convert-tsql
--- a/bin/convert-tsql
+++ b/bin/convert-tsql
@@ -1,6 +1,6 @@
 #!/bin/bash
 # Database translation/creation script
-# Copyright (C) 2009-2014, AllWorldIT
+# Copyright (C) 2009-2016, AllWorldIT
 # Copyright (C) 2008, LinuxRulz
 #
 # This program is free software; you can redistribute it and/or modify
@@ -40,7 +40,7 @@ display_usage() {
 # Check we have our params
 if [ -z "$database" -o -z "$file" ]
 then
-    display_usage
+	display_usage
 fi
 
 
@@ -48,13 +48,13 @@ fi
 # Check file exists
 if [ ! -f "$file" ]
 then
-    echo "ERROR: Cannot open file '$file'"
-    exit 1
+	echo "ERROR: Cannot open file '$file'"
+	exit 1
 fi
 
 # Check what we converting for
 case "$database" in
-		"mysql"|"mysql55")
+	"mysql"|"mysql55")
 		sed \
 			-e "s/@PREFIX@/$prefix/g" \
 			-e 's/@PRELOAD@/SET FOREIGN_KEY_CHECKS=0;/' \
@@ -67,7 +67,7 @@ case "$database" in
 			-e 's/@SERIAL_REF_TYPE@/BIGINT UNSIGNED/' < "$file"
 		;;
 
-    	"mysql4")
+	"mysql4")
 		sed \
 			-e "s/@PREFIX@/$prefix/g" \
 			-e 's/@PRELOAD@/SET FOREIGN_KEY_CHECKS=0;/' \
@@ -104,9 +104,11 @@ case "$database" in
 		;;
 
 	*)
-	    echo "ERROR: Invalid database type '$database'"
-	    exit 1
-	    ;;
+		echo "ERROR: Invalid database type '$database'"
+		exit 1
+	;;
 
 esac
+
+
 
